import argparse
from pathlib import Path

try:
    from .metric_figure_data import compute_paired_deltas, compute_summaries, load_metric_data
    from .metric_figure_output import ensure_output_dir, remove_stale_pdf_figures, write_summary_csvs
    from .metric_figure_plots import (
        plot_iou_distribution,
        plot_iou_ecdf,
        plot_iou_vs_union,
        plot_paired_delta_summary_table,
        plot_paired_deltas,
        plot_quality_distribution,
        plot_quality_vs_valid_pixels,
        plot_sequence_trends,
        plot_summary_heatmaps,
        plot_summary_table,
        set_plot_style,
    )
except ImportError:
    from metric_figure_data import compute_paired_deltas, compute_summaries, load_metric_data
    from metric_figure_output import ensure_output_dir, remove_stale_pdf_figures, write_summary_csvs
    from metric_figure_plots import (
        plot_iou_distribution,
        plot_iou_ecdf,
        plot_iou_vs_union,
        plot_paired_delta_summary_table,
        plot_paired_deltas,
        plot_quality_distribution,
        plot_quality_vs_valid_pixels,
        plot_sequence_trends,
        plot_summary_heatmaps,
        plot_summary_table,
        set_plot_style,
    )


DAVIS_SEQUENCES = ["parkour", "dance-twirl"]


def parse_args():
    parser = argparse.ArgumentParser(description="Generate publication-quality metric figures for DAVIS sequences.")
    repo_root = Path(__file__).resolve().parents[3]
    parser.add_argument(
        "--metrics-root",
        default=str(repo_root / "results" / "metrics"),
        help="Root directory containing phase/sequence metric CSV files.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(repo_root / "results" / "visualizations" / "figures" / "davis"),
        help="Directory where DAVIS figures and summary CSVs will be written.",
    )
    return parser.parse_args()


def subset_by_sequences(dataframe, sequence_names):
    return dataframe[dataframe["sequence"].astype(str).isin(sequence_names)].copy()


def assert_expected_sequences_present(iou_df, quality_df, expected_sequences):
    available_sequences = set(iou_df["sequence"].astype(str)).intersection(set(quality_df["sequence"].astype(str)))
    missing_sequences = [sequence for sequence in expected_sequences if sequence not in available_sequences]
    if missing_sequences:
        missing_text = ", ".join(missing_sequences)
        raise FileNotFoundError(
            "Missing DAVIS metric CSVs for the following sequences under the selected metrics root: "
            f"{missing_text}. Run evaluate_metrics.py for all phases first."
        )


def write_davis_manifest(output_dir):
    manifest_lines = [
        "# DAVIS Metric Figures",
        "",
        "This folder is generated by src/common/figure_scripts/generate_metric_figures_davis.py.",
        "",
        "## Scope",
        "",
        "- Sequences: parkour, dance-twirl",
        "- Phases: Part 1 Baseline, Part 2 SOTA, Part 3 Exploration",
        "- Metrics: IoU, PSNR, SSIM",
        "",
        "## Figure Inventory",
        "",
        "- 01_iou_distribution: IoU distribution figure for the DAVIS sequences parkour and dance-twirl",
        "- 02_quality_distribution: PSNR and SSIM distribution figure for the DAVIS sequences parkour and dance-twirl",
        "- framewise_metrics_parkour: frame-wise metric trends for parkour",
        "- framewise_metrics_dance_twirl: frame-wise metric trends for dance-twirl",
        "- paired_deltas_parkour: paired delta histograms for parkour",
        "- paired_deltas_dance_twirl: paired delta histograms for dance-twirl",
        "- 07_iou_ecdf: ECDF comparison for IoU",
        "- 08_iou_vs_union: scatter + linear fit for IoU versus foreground extent",
        "- 09_quality_vs_valid_pixels: scatter + linear fit for PSNR/SSIM versus evaluated background area",
        "- 10_metric_summary_heatmaps: normalized summary heatmaps for central tendency and variability",
        "- 11_metric_summary_table: report-ready descriptive summary table",
        "- 12_paired_delta_summary_table: paired improvement summary table",
        "",
        "## File Format",
        "",
        "- Figures are generated as PNG only.",
        "",
        "## Supporting Data",
        "",
        "- metric_descriptive_summary.csv",
        "- paired_delta_summary.csv",
    ]
    (output_dir / "README.md").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")


def main():
    args = parse_args()
    metrics_root = Path(args.metrics_root).resolve()
    output_dir = Path(args.output_dir).resolve()
    ensure_output_dir(output_dir)
    remove_stale_pdf_figures(output_dir)
    set_plot_style()

    iou_df, quality_df = load_metric_data(metrics_root)
    assert_expected_sequences_present(iou_df, quality_df, DAVIS_SEQUENCES)

    iou_df = subset_by_sequences(iou_df, DAVIS_SEQUENCES)
    quality_df = subset_by_sequences(quality_df, DAVIS_SEQUENCES)
    summary_df = compute_summaries(iou_df, quality_df)
    deltas_df, paired_summary_df = compute_paired_deltas(iou_df, quality_df)

    plot_iou_distribution(iou_df, summary_df, output_dir, stem="01_iou_distribution")
    plot_quality_distribution(quality_df, summary_df, output_dir, stem="02_quality_distribution")

    for sequence in DAVIS_SEQUENCES:
        plot_sequence_trends(iou_df, quality_df, output_dir, sequence)
        plot_paired_deltas(deltas_df, output_dir, sequence)

    plot_iou_ecdf(iou_df, output_dir, stem="07_iou_ecdf")
    plot_iou_vs_union(iou_df, output_dir, stem="08_iou_vs_union")
    plot_quality_vs_valid_pixels(quality_df, output_dir, stem="09_quality_vs_valid_pixels")
    plot_summary_heatmaps(summary_df, output_dir, stem="10_metric_summary_heatmaps")
    plot_summary_table(summary_df, output_dir, stem="11_metric_summary_table")
    plot_paired_delta_summary_table(paired_summary_df, output_dir, stem="12_paired_delta_summary_table")

    write_summary_csvs(summary_df, paired_summary_df, output_dir)
    write_davis_manifest(output_dir)

    print(f"Saved DAVIS figures and summary tables to {output_dir}")


if __name__ == "__main__":
    main()