def ensure_output_dir(output_dir):
    output_dir.mkdir(parents=True, exist_ok=True)


def remove_stale_pdf_figures(output_dir):
    for pdf_path in output_dir.glob("*.pdf"):
        pdf_path.unlink()


def write_summary_csvs(summary_df, paired_summary_df, output_dir):
    summary_df.to_csv(output_dir / "metric_descriptive_summary.csv", index=False)
    paired_summary_df.to_csv(output_dir / "paired_delta_summary.csv", index=False)


def write_manifest(output_dir):
    manifest_lines = [
        "# Generated Metric Figures",
        "",
        "This folder is generated by src/common/figure_scripts/generate_metric_figures.py.",
        "",
        "## Figure Inventory",
        "",
        "- 01_iou_distribution: violin + box + jittered frame samples for IoU",
        "- 02_quality_distribution: violin + box + jittered frame samples for PSNR and SSIM",
        "- 03_framewise_metrics_bmx_trees: frame-wise trends for BMX Trees",
        "- 04_framewise_metrics_tennis: frame-wise trends for Tennis",
        "- 05_paired_deltas_bmx_trees: paired delta histograms for BMX Trees",
        "- 06_paired_deltas_tennis: paired delta histograms for Tennis",
        "- 07_iou_ecdf: ECDF comparison for IoU",
        "- 08_iou_vs_union: scatter + linear fit for IoU versus foreground extent",
        "- 09_quality_vs_valid_pixels: scatter + linear fit for PSNR/SSIM versus evaluated background area",
        "- 10_metric_summary_heatmaps: normalized heatmaps for central tendency and variability",
        "- 11_metric_summary_table: report-ready descriptive summary table",
        "- 12_paired_delta_summary_table: report-ready paired improvement table",
        "",
        "## File Format",
        "",
        "- Figures are generated as PNG only.",
        "",
        "## Supporting Data",
        "",
        "- metric_descriptive_summary.csv",
        "- paired_delta_summary.csv",
    ]
    (output_dir / "README.md").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")