# For common configuration hyperparameters (视频路径、输出分辨率等等)
datasets:
  davis_root: "data/raw/davis"
  bmx_trees: "data/raw/davis/JPEGImages/480p/bmx-trees"
  tennis: "data/raw/tennis/tennis"

output_dir:
  visualizations: "results/visualizations/qualitative/part1"
  masks: "results/masks/part1"
  videos: "results/videos/part1"