# For common configuration hyperparameters (视频路径、输出分辨率等等)
datasets:
  davis_root: "data/raw/davis/DAVIS"
  davis_jpeg_root: "data/raw/davis/DAVIS/JPEGImages/480p"
  davis_annotation_root: "data/raw/davis/DAVIS/Annotations/480p"
  bmx_trees: "data/raw/bmx-trees/bmx-trees"
  bmx_trees_mask: "data/raw/bmx-trees/bmx-trees_mask"
  tennis: "data/raw/tennis/tennis"
  tennis_mask: "data/raw/tennis/tennis_mask"

output_dir:
  visualizations: "results/visualizations"
  masks: "results/masks/part1"
  videos: "results/videos/part1"